### ISSUE TITLE
faint display output, multiboot loading works fine

### ISSUE THREAD

**Issue by ShawnBusker** [rodri042/gba-remote-play#14]
Pi 3B+ running retropie.  The length of cable is only about a few inches connecting the pi to the link port.  Multiboot transfers are fine but anything beyond that results in a very faint image and controls also seem to have no effect.

**Comment by rodri042** [comment]
The RP3B+ probably needs other timings. The default ones are from my tests with a RP3B. 

Try setting lower SPI frequencies in the config files. You can check how far you can go by using the built-in benchmark.

**Comment by ShawnBusker** [comment]
It's working as intended.  I just had to configure the input inside RetroPie.
