### ISSUE TITLE
Is it possible to connect the GBA via the card solt solt？

### ISSUE THREAD

**Issue by orzgithub** [rodri042/gba-remote-play#15]
I found there's MISO, MOSI, CLK and GND in the card solt so is it possible to connect via this socket instead of the one in the ext. solt? Do these two sets of solt works in the same way?
我發現卡里有 MISO、MOSI、CLK 和 GND，所以可以通過這個插座而不是頂部的Ext.中的那個來連接？這兩組接口之間通用嗎？

**Comment by rodri042** [comment]
No, there's no way to use the serial functionality through the cartridge pins.
You could connect a Raspberry Pi to the GBA by using external hardware like an FPGA. Check out this project:

https://www.youtube.com/watch?v=l67PlzJDZz4
https://github.com/zchris9/gbarpi

Cheers!
