### ISSUE TITLE
No output on GBA

### ISSUE THREAD

**Issue by Pat93** [rodri042/gba-remote-play#17]
Hello,
I have a Raspberry Pi 3B and a Pi Zero W, I have configured both per the instructions, multiboot works, however I just get a blank screen on the GBA even after 30 minutes of waiting. I have an oscilloscope on the TX pin of the GBA and it sends data when I click "start streaming" but I get nothing back on the RX pin after the initial multiboot codes

Thanks!

**Comment by rodri042** [comment]
Hi! Try using a bigger delay in `SPI_DELAY_MICROSECONDS` or a lower `SPI_SLOW_FREQUENCY` in the configuration file.
